In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5] 

arr=np.array(my_lst) #np.array creates an array of the variable passed 

In [3]:
type(arr) #datatype of arr variable

numpy.ndarray

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.shape #no of rows and columns 

(5,)

In [6]:
#mutlinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,5,3,1]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 3, 1]])

In [8]:
arr.shape #gives us the no of rows and columns in the array 

(3, 5)

In [9]:
arr.reshape(5,3) #used to reshape the array acc to mentioned rows and columns

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [5, 3, 1]])

# Indexing

In [10]:
arr=np.array([1,2,3,4,5,6,7,8,9])

In [11]:
arr[3]

4

In [12]:
#mutlinested array
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,5,3,1]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [13]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 3, 1]])

In [14]:
arr[:,:] # : means all rows or columns depending on where it is used

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 5, 3, 1]])

In [15]:
arr[0:2,:] # 0:2 this means all the rows from 0 till 2 (2 not included) 

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [16]:
arr[:,3:]

array([[4, 5],
       [5, 6],
       [3, 1]])

In [17]:
arr=np.arange(0,10) #inbuilt function

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr=np.arange(0,10,step=2) #gap of 2    ##press shift+tab to know the params

In [20]:
arr

array([0, 2, 4, 6, 8])

In [21]:
np.linspace(1,10,50) # equally spaces 50 points from 1 to 10

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [22]:
arr=np.arange(0,10)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#copy function and broadcasting 

arr[3:]=100
print(arr)

[  0   1   2 100 100 100 100 100 100 100]


In [24]:
arr1=arr

In [25]:
arr1[3:]=500
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [26]:
print(arr) # **making changes in arr1 also affected the original array arr **

[  0   1   2 500 500 500 500 500 500 500]


In [27]:
# to prevent the above case we do the following 

arr1=arr.copy()

In [28]:
print(arr1)
arr1[3:]=1000
print(arr1)
print(arr)

[  0   1   2 500 500 500 500 500 500 500]
[   0    1    2 1000 1000 1000 1000 1000 1000 1000]
[  0   1   2 500 500 500 500 500 500 500]


In [36]:
# some conditions very useful

val=2

arr
arr<val

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [38]:
arr*val

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [39]:
arr/val

array([  0. ,   0.5,   1. , 250. , 250. , 250. , 250. , 250. , 250. ,
       250. ])

In [40]:
## we need the values which are less than val and not true and false

arr[arr<val]

array([0, 1])

In [42]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
arr*arr1

array([     0,      1,      4, 500000, 500000, 500000, 500000, 500000,
       500000, 500000])

In [44]:
np.ones(4)

array([1., 1., 1., 1.])

In [45]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [46]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
##random distribution
np.random.rand(3,3)

array([[0.77287996, 0.19175787, 0.89191403],
       [0.52768618, 0.77953413, 0.26176874],
       [0.82516594, 0.6853494 , 0.78275117]])