In [26]:
import pandas as pd
df = pd.read_csv('lec15.csv')
df.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0      1      0            113803  53.1000  C123        S   
4    male  35.0      0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [27]:
# now we drop the varaibles that dont have any impact on our data 

df = df.drop(['Name','PassengerId','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 'columns')
df.head()

Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [28]:
target = df.Survived
inputs = df.drop(['Survived'],axis='columns')

In [29]:
inputs.isnull().sum()

Pclass      0
Sex         0
Age       177
Fare        0
dtype: int64

In [30]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())

In [32]:
inputs.isnull().sum()

Pclass    0
Sex       0
Age       0
Fare      0
dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [34]:
dfle = inputs
dfle['Sex'] = le.fit_transform(inputs['Sex'])
dfle

Pclass  Sex        Age     Fare
0         3    1  22.000000   7.2500
1         1    0  38.000000  71.2833
2         3    0  26.000000   7.9250
3         1    0  35.000000  53.1000
4         3    1  35.000000   8.0500
..      ...  ...        ...      ...
886       2    1  27.000000  13.0000
887       1    0  19.000000  30.0000
888       3    0  29.699118  23.4500
889       1    1  26.000000  30.0000
890       3    1  32.000000   7.7500

[891 rows x 4 columns]

In [35]:
X = dfle
X = np.array(X)
X

array([[ 3.        ,  1.        , 22.        ,  7.25      ],
       [ 1.        ,  0.        , 38.        , 71.2833    ],
       [ 3.        ,  0.        , 26.        ,  7.925     ],
       ...,
       [ 3.        ,  0.        , 29.69911765, 23.45      ],
       [ 1.        ,  1.        , 26.        , 30.        ],
       [ 3.        ,  1.        , 32.        ,  7.75      ]])

In [36]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [37]:
ct = ColumnTransformer([('Sex',OneHotEncoder(),[1])],remainder = 'passthrough')

In [38]:
X=ct.fit_transform(X)
X

array([[ 0.        ,  1.        ,  3.        , 22.        ,  7.25      ],
       [ 1.        ,  0.        ,  1.        , 38.        , 71.2833    ],
       [ 1.        ,  0.        ,  3.        , 26.        ,  7.925     ],
       ...,
       [ 1.        ,  0.        ,  3.        , 29.69911765, 23.45      ],
       [ 0.        ,  1.        ,  1.        , 26.        , 30.        ],
       [ 0.        ,  1.        ,  3.        , 32.        ,  7.75      ]])

In [39]:
X = X[:,1:]
X

array([[ 1.        ,  3.        , 22.        ,  7.25      ],
       [ 0.        ,  1.        , 38.        , 71.2833    ],
       [ 0.        ,  3.        , 26.        ,  7.925     ],
       ...,
       [ 0.        ,  3.        , 29.69911765, 23.45      ],
       [ 1.        ,  1.        , 26.        , 30.        ],
       [ 1.        ,  3.        , 32.        ,  7.75      ]])

In [40]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(inputs,target,test_size=0.3)

In [41]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [42]:
model.fit(X_train,y_train)

GaussianNB()

In [43]:
model.score(X_test,y_test)

0.7835820895522388

In [44]:
model.predict(X_test[0:10])

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [45]:
y_test[0:10]

333    0
524    0
266    0
87     0
365    0
247    1
201    0
747    1
77     0
23     1
Name: Survived, dtype: int64

In [46]:
model.predict_proba(X_test[:10])

array([[0.94994023, 0.05005977],
       [0.96181499, 0.03818501],
       [0.93307146, 0.06692854],
       [0.96184988, 0.03815012],
       [0.96195994, 0.03804006],
       [0.22409677, 0.77590323],
       [0.87091024, 0.12908976],
       [0.2414298 , 0.7585702 ],
       [0.96184988, 0.03815012],
       [0.72659064, 0.27340936]])

In [47]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=5)

array([0.808     , 0.768     , 0.776     , 0.75      , 0.78225806])