In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df = pd.read_csv('lec3.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

now we can observe that there is a null value in df so firstly we need to handle that 
here we will find the median of the available data and insert it in null positio

In [5]:
df['bedrooms'].median()

3.5

we need whole number so 

In [6]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [7]:
#df['bedrooms'] === df.bedrooms

df['bedrooms'] = df['bedrooms'].fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [9]:
reg.coef_ ## reg = m1*area + m2*bedrooms + m3*age +b

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
reg.intercept_

383725.0

In [11]:
reg.predict([[3000,3,40]])

C:\Users\risha\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

# EXERCISE

In [12]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [13]:
df = pd.read_csv('hiring.csv')

In [14]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [15]:
df.experience = df.experience.fillna('zero')

In [16]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [17]:
from word2number import w2n

In [19]:
 df.experience = df.experience.apply(w2n.word_to_num)

In [20]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [22]:
df.isnull().sum()

experience                    0
test_score(out of 10)         1
interview_score(out of 10)    0
salary($)                     0
dtype: int64

In [24]:
import math
test_score_mean = math.floor(df['test_score(out of 10)'].mean())

In [25]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(test_score_mean)

In [26]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [27]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [28]:
reg.predict([[2,9,6]])

C:\Users\risha\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])